apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helmrepository.yaml

  - ../apps/test-flux/test-flux-default.yaml
  - ../apps/test-flux/test-flux-ite.yaml

  - ../apps/portfolio/portfolio-default.yaml
  - ../apps/portfolio/portfolio-ite.yaml